### PR TITLE
Textbook Alignment Template

### PR DESCRIPTION
**Pull request by schanzer**
This PR tracks all the tweaks to our textbook alignment template.

NOTE: page-breaks need to be manually inserted!! In other words, you need to know which row is the last on the page, and specify that in the CSS towards the top of the file.

### CODE REVIEW

**Comment by retabak** [comment]
CMP grade 6 looks good! I do think the box plot with the transparent background looks a little funny. Didn't it have a whitebackground before?

CMP grade 7:
- Last sentence of introductory paragraph still says, "Teaching 6th grade math..." (needs to be revised to include relevant 7th grade CS standards, I assume?)
- This image looks weird:
image
(I'm not sure why as it looks totally normal on the CMP6 one-pager?)
- Are we missing images because they need to be uploaded first?
- Typos in the bottom box (code for bullets didn't work out?):
image
- I tried printing to a PDF (there's no other way to view PDF, right?) and noticed that the footer (NSF logo and our website) appeared on page 1 and 2, definitely interrupting the important content. Can it just go on the last page / will there be a better way of turning this into a PDF?

**Comment by flannery-denny** [comment]
@schanzer Thanks for getting the pdf build up and running for this! I'm going to agree with @retabak that:

- The footer doesn't make sense on the first page
- I'm unclear as to why the images from [this google doc](https://docs.google.com/document/d/17fT88WDmr-Gs-ZfNlWmuuwlLMl9AcUInZJyUDUXG0Nk/edit?usp=sharing) didn't get ported over.  
- It looks like the page break is being defined in the wrong place. 

I'll see if I can figure out how to make those changes and am hopeful that once the images are added there will be a lot less whitespace to deal with and we'll be able to fill it through some combination of adjusting the font size in the table and word smithing.

@retabak - to keep you in the loop, you can now see pdfs of these files using `./build-pathway __sample --book`

**Comment by flannery-denny** [comment]
@schanzer passing the baton back to you to figure out scaling so that the page breaks at the line I told it to and eliminating the footer on page 1.

**Comment by schanzer** [comment]
@flannery-denny 

1. Why doesn't the footer make sense on the first page? It's the same footer as the second page - is there something wrong there, too?
2. Do you have the original files you used to make those images? I don't know of any way to export images from a google doc, so I don't have access to those files.
3. Where should the page break be?

JFYI - adding a running footer to every page is really pushing the limits of what CSS can do.

**Comment by flannery-denny** [comment]
@schanzer 

1. @retabak and I agree that there shouldn't be a footer on the first page because it makes it feel like the document has ended.
2. I added the images to the file last week - can't you see them?
3. I can't find the file... but I put the line number in the css where I thought it should break... pretty sure that when I build the `--sample` pathway from `master` I should see it in resources... but I'm not finding it there or in sublime. If you can't see the line in the asciidoc, can you remind me where to look to see the file?

**Comment by flannery-denny** [comment]
Also, can we add the issue about one-pagers to this pull request and close the issue?

**Comment by schanzer** [comment]
@flannery-denny where are these image files right now?

I've updated both pages to put the footer only on the last page, which GREATLY simplifies the CSS. Page breaks can now just happen automatically

**Comment by flannery-denny** [comment]
@schanzer I added these to the image folder for resources in the sample
pathway last week. At this point I have no idea where to even find the
asciidoc for this page. Are you working on a separate branch that I need to
checkout to? If you can help me find it, I can find the image files that I
added to the accompanying folder or reupload them to that folder.

**Comment by schanzer** [comment]
@flannery Nothing has changed - it's all on the textbooks branch, and I haven't moved any image files

**Comment by flannery-denny** [comment]
switched to the textbooks branch and all the images are exactly where I put
them.

**Comment by schanzer** [comment]
@flannery-denny I'm sorry, I'm kind of confused. All of the images in that folder are ones that I created from screenshots (not ideal), or remade myself. Are you sure you checked in your own files? If you see them there, would you mind changing the `@image{}` directives to use the ones you think they should use?

**Comment by schanzer** [comment]
@retabak and @flannery-denny - these templates are done, so I'm going to merge the PR. At this point we should put some cycles towards wrapping up the alignment docs (for IM especially). Do you want me to open a separate issue, or do you want to track that on your own?

**Comment by flannery** [comment]
Unsubscribe.

**Pull request merged**
