### PR TITLE
Fall2022 flex

### PR DESCRIPTION
**Pull request by schanzer**

### CODE REVIEW

**Comment by schanzer** [comment]
@flannery-denny and @retabak , this PR is ready for review! After tweaking more than 170 files, I can confirm that:

- nothing bleeds onto two pages
- virtually every `fitb` that _can_ use the flexible model now _is_
- every page has had a quick scan, and all glaring visual problems have been fixed

I propose that you do a quick scan as well, before we merge this. We'll be doing a careful error check anyway once the fall2022 authoring is complete, and we'll catch any small things then.

**Comment by flannery-denny** [comment]
@schanzer Seems like a good plane task for tomorrow.
- Clarifying - what's the name of the branch that I should checkout to?
- Do you want me to do a full ./build-pathway and check all of the materials I can think of that are most likely to be buggy or are there particular things you'd like me to be looking at / for?

**Comment by schanzer** [comment]
@flannery-denny good call! 

Everything is on the `fall2022-flex` branch (the branch in question is _always_ listed at the top of a pull request like this one). I would build the OK pathway and explore `workbook-long.pdf`. This includes a _huge_ percentage of our WB pages, so once it's looking good I think we'll be in great shape to merge.

JFYI - I just re-sync'd this branch with fall2022, but I haven't converted any of your new material to the new format.

**Comment by retabak** [comment]
- [ ] page 10
image

- [ ] page 14 - some lines don't extend to end
image

- [ ]  page 17 - should the lines be closer to the triangles?
image

- [ ]  page 20 - no lines for composition and operations
image

- [ ] page 27 - line doesn't extend to end.
image

- [ ] page 30 - nothing WRONG with this formatting, but it's different from how the other Circle of Eval pages are formatted (with a line on which students write their code)
image

- [ ] Design recipe (unnumbered, between pages 35 and 36) / issue on all DRs: do we want circled lines to extend to the end of the page?
image

- [ ] page 56 - are answers supposed to show up? (They do.)

- [ ] page 59 - no room to notice and wonder: 
image

- [ ] There are three unnumbered pages between 61 and 62. The first of them also has the issue as above (no room to notice and wonder).

- [ ] page 77 - extra indentation
image

- [ ] page 81 - change periods to colons or delete them
image

- [ ] unnumbered page between 95 and 96 looks like this:
image

- [ ] There are four unnumbered pages between 110 and 111; the first one (`species-dot`) has answers on it.

- [ ] page 112
image

- [ ] page 124 "PAGE NOT FOUND!"

**Comment by flannery-denny** [comment]
@schanzer 
*The OK Workbook looks impressively good!*
- [ ] The flex fitb seems to use a different amount of vertical space than the old one. I was noticing that the printed part of many pages is shorter than in previous versions, but looking at the what’s on your mind page really clinched it. Those lines are too close together to write on, and the lines used to fill the page rather than be concentrated in the top 55% of the page.
*The only other pages that seems to have a @fitb related issues are:*
- [ ] Boolean functions the blank spaces are way too small!
- [ ] Why don’t all of the lines on the Data Cycle pages make it to the right side
- [ ] Part of the solutions have been revealed on Reflection on Form, Direction and Strength
_I of course have a separate list of things that I noticed and will make an issue listing them._
- [ ] The pdf build on the fall2022-flex branch does not appear to be stable yet, see error messages on slack
- [ ] I’m getting a warning about this page.
head: pages/MappingExamplesWithCoE.adoc: No such file or directory
Looks like perhaps I lost it trying to resolve a merge conflict? 
But maybe it still exists on fall2022 and the issue will be resolved through the next merge?

**Comment by schanzer** [comment]
@flannery-denny the vertical space has change to be more uniform, which I admit may not be a good thing! In almost all workbook pages, we've generally given about a line-and-a-half of vertical space. But in whats-on-your-mind, we've upped this to 2 lines.

I have two options in front of me for how to fix this:

**1) Bring back `.blankline`, and give it a different height than other blanks** - This means extra markup/css. Not a huge deal, but a little annoying.

**2) Change the height of all blanks, everywhere** - This will cause almost all of our pages to spill into two lines. I just did a quick experiment and I'm seeing 104 that will need to be revised. And these revisions are much more involved than tweaks, since we're actually changing the fundamental line-height everywhere. I really do NOT want to do this.

**3) We give kids thinner lines, adding more to fill up the remainder of the page** - I'm most in favor of this option. Remember, we _already_ ask kids to write in smaller lines throughout the workbook! It's really just the fill-in-the-blank pages where we've given them more room.

--
The Data Cycle is still being tweaked on the fall2022 branch, so I haven't bothered to move it to the flex format yet. Doing so is easy, but I want to make sure it's done before I start changing stuff.

Let's hop on zoom sometime to check out the build error you're seeing? I can't replicate on my machine. (Have you tried deleting the whole distribution directory?)

Which Boolean function page are you referring to?

**Comment by schanzer** [comment]
@flannery-denny I pushed a change that gives us a little more space, particularly in the whats-on-your-mind pages. Let me know what you think?

**Comment by flannery-denny** [comment]
@schanzer I don't have access to a printer, but...

I think the spacing on what's on your mind looks much better, 
- [ ] except that the top line doesn't have enough space between it and the title... 
- [ ] and we need to add enough lines to fill in the rest of the page.

**At a quick glance, I'm noticing that** 
- [ ] the lines on Boolean Functions look very close together.
- [ ] There's something really missed up about the way the text beneath the lines on the shape of my dataset and several other data cycle pages is aligning left instead of center and getting cut off.
- [ ] the tables on most of the Notice & Wonder pages aren't filling the page so we'll need to add more vertical space

**Comment by flannery-denny** [comment]
@schanzer On analyzing categorical data, the icons aren't showing up for me. and the lines continue partway onto the following line.

**Comment by flannery-denny** [comment]
@schanzer Noticing that word-problem-sex-dot from custom scatterplot has the word `end` showing up on top of the Definition title.

**Comment by schanzer** [comment]
@flannery-denny I've fixed the line-widths in data cycles, and I'm trying to find the issue with images not showing up for that one DC. As for `end` showing up above the Definition title -- it's _always_ been there. Where else would you put it?

**Pull request merged**
