### PR TITLE
MathJax3

### PR DESCRIPTION
**Pull request by schanzer**
This PR moves us from v2 to v3, and is designed to address a number of issues:

- The "roof of the house" in the Square Root symbol displaying/printing incorrectly in certain cases (see #1294)
- Lettering is inconsistently sized (see #1294)
- Clean up some technical debt from using an ancient library
- Improve page load times - and therefore PDF generation speed! (MathJax3 is more than 2x as fast, which shaves ~100ms off each page)
- Reduce the size of our JS dependencies (MathJax3 is modular and can be tree-shaken)

### CODE REVIEW

**Comment by retabak** [comment]
I did a quick once-over. Here are some thoughts:

- [ ]  Why is the "roof of the house" on the square root symbol sometimes (not always) so dark now?! I suppose it's better than before! (This is page 17 of workbook-long-sols; it appears normal, however, on page 32.)

image

- [ ]  Arithmetic Exp to COE and Code - challenge 2 needs wider first column
- [ ] **SOMETHING WEIRD happening on p. 75**

image

- [ ]  Just noticed that the solutions for "Welcome to Alice's Restaurant" are all wescheme?!? Has that always been the case?
- [ ]  Challenge: Character Movement in Two Directions -Q1 needs `update danger` to be hyphenated.
- [ ] Oooh, those radical signs on page 107 look GREAT!
- [ ] UGGHHHHH just noticed the Circle of Eval on page 108 doesn't have lins separating the function from the rest of the circle. 
- [ ] Last page of contracts has several lines with two # rather than one. (I corrected this for the linse that have contracts, but not for the blank lines.)

**Comment by schanzer** [comment]
@ds26gte looks like Rachel found a bug related to mathjax generation. In `function-definition-linear/pages/definitions-from-tables.adoc`, we're getting raw HTML output like this:

`${empty}$\displaystyle f(x) =${empty}$`

This looks like a possible preproc issue. Can you investigate?

**Comment by schanzer** [comment]
@retabak you wrote " Arithmetic Exp to COE and Code - challenge 2 needs wider first column". Why? Does one of the lines wrap for you?

**Comment by ds26gte** [comment]
> @ds26gte looks like Rachel found a bug related to mathjax generation. In `function-definition-linear/pages/definitions-from-tables.adoc`, we're getting raw HTML output like this:
> 
> `${empty}$\displaystyle f(x) =${empty}$`
> 
> This looks like a possible preproc issue. Can you investigate?

Looks like generating `${empty}$` in the `.asc` file with the expectation that it will get converted to simple `$$` in the HTML doesn't always work. I've reverted to generating a marker and then converting it during postproc to `$$`. However, the marker is simpler than the previous 3-part markers, since we only need something to stand in for `$$`.  

Fix in commit ad929b91b in branch MathJax3.

**Pull request merged**
