### PR TITLE
Align Screen and Print font sizes across all pages (closes #1223)

### LINKED ISSUE #1223: Font Size Overhaul
AsciiDoctor injects a ton of extra rules, which we've been slowly-but-surely overriding. Here's a new one:

In Print view, asciidoctor messes with the global font size in some weird ways. This has the effect of making _some_ text items about 20% smaller - most notably within circles of evaluation - leading to inconsistencies between printed and digital versions of these pages.

We need to remove these rules, and then deal with every page that breaks as a result

While I'm at it: 
- [x] investigate making https://github.com/bootstrapworld/curriculum/commit/32e958837a29b584812ef546dc6a7dd16412781e global

### PR DESCRIPTION
**Pull request by schanzer**
For regressions, please use the following reporting conventions:

- Tell me the lesson and page name (not the workbook page num, or which workbook)
- Briefly describe the issue, and whether the problem occurs in screen mode, print mode, or both
- Add a screenshot of the problem, along with one of the "correct" page live on our website

### CODE REVIEW

**Comment by retabak** [comment]
Just did a very cursory scan. I am going to go back and look closer! Here are some issues that jumped out at me immediately, without pulling out the fine tooth comb...

**Issues in lessons:**

- [ ] On all course landing pages, the font size is too small.
- [ ] In the customized dictionary on each lesson page, the font size for vocab words is too small. The word "Glossary" is also too small. Screenshot below.

image

- In the sidebar in all lessons, the font size is too small for lesson names and standards text.

**Issues in Workbook** 

- [ ] There are many instances where the font size of the code text (anything that is inside tick marks) is way too small. In these cases, the code font's height is about half the height of the normal text. Here are a few instances (definitely not all) to illustrate:

- from functions-dr, rocket-challenges.adoc
image

- from inequalities1-simple, boolean-functions.adoc
image

- You should know that the tiny code font is not ALWAYS an issue. For instance, it looks fine in problem-decomposition, profit-discussion.adoc ... and in several other places: 
image

Let me know if you need more examples! Or if I actually need to go through and list every single instance (which would take forever).

- [ ] There's some weird stuff going on in combinatorics-combination, combination.adoc. I tried to highlight in green some of the weirdness.

image

- [ ] Notes pages. I remember we did some work to make them take up more space and not leave so much white space. That seems like it didn't stick after these updates?  Example from notes-threats-to-validity.adoc:

image

**Comment by schanzer** [comment]
@retabak I've fixed the font size issues you raised in the vocabulary, landing page, and sidebar. All code font should also back to normal on all workbook pages. Thanks for this!

The notes pages haven't changed at all from `master` so this is no different from what they've always been. If you'd like to change them, open a separate issue.

Good catch on the combinatorics pages! It looks like an interaction between @ifsoln{} and @math{}. I'll open a separate issue for Dorai.

Ready for your second review!

**Comment by retabak** [comment]
I'm actually not finding a whole lot of problems :)
Here are some new things...

*Web materials:*

The font sizes of lesson titles (at the top of all lesson pages), and "Overview", "Launch", "Investigate", and "Synthesize" are smaller than on the web.

Algebra Pyret glossary - these examples got cut off? I checked the asciidoc and the web and they are there!

image

definition cut off?! In the asciidoc, the end of the sentence is typed like this: `\"independent variable\"`
image

*Okay, THERE IS A PATTERN*, and I see a handful of other instances in this glossary: *Stuff typed inside \ \ disappears!*

Teacher Resource page (I'm looking at algebra): "All Lesson Notes" are not there!
image



*Workbook pages:*

Hmm.... the first line on "Windows and Mirrors" worksheet is too bold. 

image

Code font still looks too small here in order-of-operations, translate-coe-to-code-w-sqrts.adoc:
image

.... and many other places.

**Comment by schanzer** [comment]
@retabak thanks for this! I believe all of the issues related to this PR have now been fixed. 

The glossary and notes regressions have been split out into other issues.

**Comment by schanzer** [comment]
@retabak Dorai has fixed all of those other issues. I'll merge this in after uploading a refreshed copy to Lulu

**Comment by flannery-denny** [comment]
@schanzer would you like me to weigh in on this?

**Comment by schanzer** [comment]
@flannery-denny that would be great! Are you basically blocked waiting for me to weigh in on the other issues?

**Comment by flannery-denny** [comment]
@schanzer I checked out to the branch and started looking at things. I am seeing that there are some things that I know have been fixed on master (ie the size of the "Glossary" title) that are not fixed on this branch, makes me wonder if it's really productive to do the work on this branch.

One thing I'm noticing right off the bat is that the right margins of the text in the grey boxes on the lesson plans appear to be quite narrow. This example is from Computing Needs all Voices.
Screen Shot 2023-08-01 at 9 14 36 PM

**Comment by flannery-denny** [comment]
@schanzer the Language Table link produces a miniature version of the language table.
Screen Shot 2023-08-01 at 9 25 27 PM

**Comment by flannery-denny** [comment]
On the web and in pdfs, the data cycle pages, question type and circle one are not centered
Screen Shot 2023-08-01 at 9 28 34 PM

**Comment by flannery-denny** [comment]
The text beneath `fitbruby` and the title of the page in design recipes (both pdf and on the web) is much smaller than it was in spring2023.  

Here's an example from Grouped Samples. I think it's related to the issue I was raising with the Data Cycle pages.

Screen Shot 2023-08-01 at 9 55 44 PM
Screen Shot 2023-08-01 at 9 56 08 PM
Screen Shot 2023-08-01 at 9 57 50 PM

**Comment by flannery-denny** [comment]
There's a new discrepancy in code sizes that didn't exist in spring2023 materials.
See the font sizes of the function definitions as compared to the table contents in these examples from Method Chaining (size nearly equal) as compared with Table Operations (size nearly double)
Screen Shot 2023-08-01 at 10 04 57 PM
Screen Shot 2023-08-01 at 10 05 21 PM

Screen Shot 2023-08-01 at 10 05 08 PM

**Comment by schanzer** [comment]
@flannery-denny I've pushed a commit that should address all of these issues

**Pull request merged**
