### PR TITLE
Vertical spacing for tables and lines (fixes #840)

### LINKED ISSUE #840: We need variable-height paragraphs and revised flex-css for tables
The `fall2022-flex` merger bought us _horizontal_ flexibility: blank lines can now stretch to the end of the page, regardless of where they began.

However, this came at a cost: we lost _vertical_ flexibility, so every line has a fixed height. 99% of the time this is fine, but there are several corner cases where we'd like the lines to be taller (e.g. - "what's on your mind?" pages, and others). So far, the only CSS solution I've found requires a fixed _minimum height_ -- it solves all of our problems, but empty lines that used to take up no vertical space now **do**. And that breaks a lot of pages, by added extra height.

### PR DESCRIPTION
**Pull request by schanzer**
Oh man, this one was interesting! 

So the bottom line is that HTML `table` elements simply will not do what we want. However, there's a modern CSS rule called `display:grid`, which simulates tables and _will_ do what we want. The only problem is that AsciiDoctor only generates `table`, plus we have hundreds and hundreds of `table`s and it would be insane to remove them.

The tricky part here was figuring out way to make HTML tables use `display:grid`, and it took quite a bit of time. But once that was done, it was just a matter of reformatting hundreds of wbpages to use it! ;) 

Not only does this allow our pages to look a lot nicer (more room for kids to write, every table ends at the exact bottom of the page, etc), but it _also_ removes a ton of brittle CSS and `@vspace` junk from our wbpages! In fact there's more than _four hundred lines of junk_ removed across nearly _two hundred_ pages.

Given the enormous number of changes, this could really use some review to make sure PDFs print correctly. I've gone through the extended Oklahoma workbook (which includes DS and A) and checked pretty carefully, but CODAP and WeScheme pages haven't gotten as much attention as they deserve. Perhaps the best way is to divide and conquer?

---------------------- UPDATE 10/6---------------
Finally, after nearly 18 months of on-again, off-again experiments: **_Variable height lines work!_**🎉

This has a number of benefits:

1. It saves us an additional 200+ lines of junk CSS that was used to artificially add space for fill-in-the-blanks.
2. We'd previously needed to hardcode a single line-height that was tall enough for kids to write stuff, but short enough so that wbpages didn't spill onto a second page. Now we can grow only the lines that need to be tall, and let the rest be shorter than they were before. This saves us a bunch of space in a bunch of pages.
3. The pages that are most impacted by this benefit are the Design Recipe pages, which previously used a hideously complex set of hardcoded paddings, heights, and margins to make everything fit right. A lot of the ugliest CSS hacks have now been removed, though there's room for a lot more cleanup in the future.

### CODE REVIEW

**Comment by flannery-denny** [comment]
@schanzer I can't tell from this request whether I should be building `flex-wbpages` or `master`. I can review the pdfs on the plane tomorrow if I know which to build. `algebra-wescheme` ?

**Comment by retabak** [comment]
you mentioned dividing and conquring, @schanzer . Should I do CODAP? Check over the work that's been done? Let me know!

**Comment by flannery-denny** [comment]
@schanzer Mostly looks good. Here are a few pages from the `WeScheme Algebra workbook-long` that look strange

- [ ] p19 `Numbers n Strings` formatting is wonky
Screen Shot 2022-10-06 at 2 37 05 PM

- [ ] unrelated to your pull request, but any idea why the `domain and range frayer model` appear on both page 22 and 29
- [ ] also unrelated to your pull request, but any idea why the extended contract formatting on `star-polygon` is different from `triangle contracts`?
- [ ] `Which values would make sense to define` - there's random text that read "Source:275"
Screen Shot 2022-10-06 at 2 44 04 PM

- [ ] p73/46 `Describe and Define your own variables` `?FITB` is bleeding through
Screen Shot 2022-10-06 at 2 45 49 PM

- [ ] p88/60 `Matching Examples and Function Definitions` and 89/61 `Creating Contracts From Example` formatting of code is inconsistent
- [ ] p151 `Onscreen more than one way` - indentation is off for **Sabra's Thinking**.
Screen Shot 2022-10-06 at 3 01 33 PM
- [ ] p159 `Welcome to Alice's Restaurant` - this table doesn't extend to the bottom of the page.
- [ ] p161 `Word Problem: Alice's Restaurant` header formatting is wonky
Screen Shot 2022-10-06 at 3 05 16 PM

**Comment by flannery-denny** [comment]
@schanzer looking at the `Wescheme algebra workbook-long solutions`

- [ ] Italicization underscores are showing on `Numbers n strings` a page that also had weird formatting in the regular workbook version.
Screen Shot 2022-10-06 at 3 12 15 PM

- [ ] `More than one way to Compose an Image!` challenge solution is being cut off
Screen Shot 2022-10-06 at 3 13 16 PM
- [ ] `Describe and Define your own variables` **FITB?**

**Comment by schanzer** [comment]
@flannery-denny thanks for this! I'm kind of shocked this was all you could find, and that almost all of these issues were already problems on master!

- The `FITB?` showing through is definitely a bug in the build script, and I've opened a new issue to track it (#1156).
- The second appearance of the frayer-model _should_ be using the page for function and variable. I don't know why it's duplicating the first frayer page. **@ds26gte you may need to weigh in here**
- I can't get numbers-and-strings to show that funky gap. **Can you try rebuilding?**
- You have two points here about formatting differing between two workbook pages, but in both cases those pages are so different that I wouldn't expect them to have the same format. **Can you say more about what looks "off" to you?**
- The "more than one way" glitch that you saw is related to the flexible-height CSS plague, which I fully expected to take at least a full month to fix. I'm kind of in shock that the lessons I learned from the flexible-table problem were so directly applicable, and I fixed it this morning! So now that glitch is gone -- sorry I wasn't able to fix it before you printed to PDF!

**Comment by retabak** [comment]
Looking at this tomorrow! Sorry I'm slow!

**Comment by flannery-denny** [comment]
@schanzer it's the code that's formatted inconsistently. Here are the three variations i see on page 88 and 89 of the long workbook.
Screen Shot 2022-10-07 at 10 23 11 AM
Screen Shot 2022-10-07 at 10 23 04 AM
Screen Shot 2022-10-07 at 10 22 59 AM

**Comment by flannery-denny** [comment]
@schanzer and here's how star-polygon and triangle contract code is formatted differently

Screen Shot 2022-10-07 at 11 15 27 AM
Screen Shot 2022-10-07 at 11 14 57 AM

**Comment by flannery-denny** [comment]
@schanzer pulled your most recent changes (had pulled midday yesterday and rebuilt before providing that other feedback) and I'm seeing a lot of pages that aren't fitting one one page

> 📎 COLLATING WORKBOOK PAGES
> -----------------------------------------------------------
> 
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/computing-needs-all-voices-wescheme/pages/computing-pioneers.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/computing-needs-all-voices-wescheme/pages/windows-mirrors.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/numbers-inside-video-games-wescheme/pages/ReverseEngineerGame.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/coordinates-wescheme/pages/BrainstormGame.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/order-of-operations-wescheme/pages/complete-coe-from-arith.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/order-of-operations-wescheme/pages/match-arith-coe.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/order-of-operations-wescheme/pages/complete-code-from-coe.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/order-of-operations-wescheme/pages/match-coe-to-code.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/order-of-operations-wescheme/pages/matching-coe-exp.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/order-of-operations-wescheme/pages/coe-to-arith.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/order-of-operations-wescheme/pages/coe-to-arith2.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/order-of-operations-wescheme/pages/evaluate-coe.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/order-of-operations-wescheme/pages/evaluate-coe2.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/order-of-operations-wescheme/pages/coe-to-code.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/order-of-operations-wescheme/pages/coe-to-code2.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/simple-data-types-wescheme/pages/notes-intro-to-programming.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/simple-data-types-wescheme/pages/booleans.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/contracts-wescheme/pages/applying-functions.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/contracts-wescheme/pages/practicing-contracts.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/contracts-wescheme/pages/using-contracts.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/contracts-wescheme/pages/triangle-contracts.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/contracts-wescheme/pages/radial-star.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/contracts-wescheme/pages/whats-on-your-mind.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/function-composition-wescheme/pages/function-composition-green-star.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/function-composition-wescheme/pages/function-composition-your-name.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/function-composition-wescheme/pages/function-composition-scale-xy.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/function-composition-wescheme/pages/more-than-one-way.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/defining-values-wescheme/pages/chinese-flag.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/defining-values-wescheme/pages/coe-why-define-values.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/defining-values-wescheme/pages/which-value-to-define.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/flags-wescheme/pages/japan-estimating-coordinates.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/flags-wescheme/pages/decomposing-flags.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/making-game-images-wescheme/pages/NoticeAndWonder.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/functions-make-life-easier-wescheme/pages/define-your-own.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/functions-make-life-easier-wescheme/pages/whats-on-your-mind.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/functions-vertical-line-test-wescheme/pages/functions-graphs.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/functions-vertical-line-test-wescheme/pages/functions-graphs-2.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/functions-vertical-line-test-wescheme/pages/how-tables-fail-vertical-line-test.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/functions-vertical-line-test-wescheme/pages/functions-tables.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/functions-vertical-line-test-wescheme/pages/functions-tables-graphs.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/function-notation-wescheme/pages/match-examples-definitions-math.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/function-notation-wescheme/pages/function-notation-substitution.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/function-notation-wescheme/pages/function-notation-graphs.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/function-notation-wescheme/pages/function-notation-tables.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/function-notation-wescheme/pages/function-notation-graphs-pw.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/functions-examples-definitions-wescheme/pages/whats-on-your-mind.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/functions-examples-definitions-wescheme/pages/MappingExamplesWithCoE.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/functions-can-be-linear-wescheme/pages/notice-wonder-linearity.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/functions-can-be-linear-wescheme/pages/match-tables-graphs.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/functions-can-be-linear-wescheme/pages/graphs-all-linear.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/functions-can-be-linear-wescheme/pages/tables-all-linear.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/functions-can-be-linear-wescheme/pages/linear-nonlinear-bust.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/functions-can-be-linear-wescheme/pages/slope-int-tables-intro.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/functions-can-be-linear-wescheme/pages/slope-int-tables-basic.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/functions-can-be-linear-wescheme/pages/slope-and-y-tables.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/functions-can-be-linear-wescheme/pages/slope-and-y-graphs.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/functions-can-be-linear-wescheme/pages/match-tables-graphs2.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/functions-can-be-linear-wescheme/pages/linear-nonlinear-bust-graphs.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/functions-can-be-linear-wescheme/pages/linear-nonlinear-bust-graphs-2.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/functions-dr-wescheme/pages/create-examples-contracts-purpose-1.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/functions-dr-wescheme/pages/dr-blank.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/problem-decomposition-wescheme/pages/topdown-bottomup-discussion.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/inequalities2-compound-wescheme/pages/boolean-coe-to-code1.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/inequalities2-compound-wescheme/pages/and-or.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/inequalities2-compound-wescheme/pages/compound-inequality-solutions.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/inequalities2-compound-wescheme/pages/boolean-coe-to-code2.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/inequalities3-sam-wescheme/pages/onscreen-discussion.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/piecewise-functions-conditionals-wescheme/pages/mood-generator-dr.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/piecewise-functions-conditionals-wescheme/pages/restaurant-intro.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/player-animation-wescheme/pages/2d-character-movement-cont.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/distance-formula-wescheme/pages/distance-write-code-from-lengths.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/distance-formula-wescheme/pages/distance-on-coordinate-plane.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/distance-formula-wescheme/pages/distance-coe.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/distance-formula-wescheme/pages/distance.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/distance-formula-wescheme/pages/distance-comparing-code.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, back-matter/pages/contracts-1.pdf has 2 pages
> WARNING: in algebra-wescheme workbook-long.pdf, back-matter/pages/contracts-2.pdf has 2 pages

**Comment by schanzer** [comment]
@flannery-denny this is interesting - the contract code for `star-polygon` and `triangle-asa` sometimes renders identically...and sometimes doesn't. There's something nondeterministic happening in the build! Opening a new issue for Dorai

**Comment by schanzer** [comment]
@flannery-denny solved the frayer model issue, then solved it in a much, MUCH better way

**Comment by retabak** [comment]
Here's the weird stuff I'm seeing in workbook-long in the data-science-codap pathway:

page 9 - italics underscores showing up: (PDF p13)
image

p13, 14, and 15 (PDF p17) - It might be nice for these to fill up the whole page:
image

p26 - can this fill up the page to allow more room to write?
image

p.22 - 25 (PDF p28-31)- seems weird to have all that empty space before the first section begins.
image

yikes - some weird stuff here! (PDF p37)
image

and here (PDF p40)
image

Also, there's some funny page numbering issues? Some pages don't have numbers. Is that right?

**Comment by schanzer** [comment]
@retabak I've pushed a change that should address these issues. Let me know if they're resolved, when you get a chance?

**Pull request merged**
