### PR TITLE
Collapsible Exercises and Solutions 

### PR DESCRIPTION
**Pull request by schanzer**
I couldn't wrap my head around the more-important authoring issues today, but didn't want to be useless, so I went ahead and implemented #1965 , making the following changes:

1. Adds optional and required page titles and filepaths to the dependency graphs
2. Uses that information to dynamically populate the materials lists on lesson pages (one less thing happening statically!)
3. Uses that information to dynamnically populate the "exercises and solutions" section of the TR page
4. Aligns the DOM, CSS and JS for collapsible page lists so that collapsibility can be re-used for TR page
5. Makes the lessons under "exercises and solutions" collapsible, thereby implementing the issue

@retabak and @flannery-denny - can you take it for a spin? (reminder: open the _pathway page_ and then click "teacher resources", rather than opening TR page directly

@ds26gte this removes any need for the `materials` and `opt-materials` cache files. I suspect there's a decent amount of build code for creating and handling them that can now be removed.

### CODE REVIEW

**Comment by flannery-denny** [comment]
@schanzer The way the exercises appear on the teacher resources page looks fine to me, but even after make book I am not able to open the exercises or solutions, so I cannot confirm that it actually works.

**Comment by schanzer** [comment]
@flannery-denny great! I've fixed the links. I'll wait to merge until @retabak weighs in

**Comment by flannery-denny** [comment]
@schanzer that was fast!  l logged on to add that I should have commented with far more enthusiasm before. This is a huge improvement in usability for teachers!Links work for me now in TR and lesson plans.

One small noticing is that there's a significant vertical space between the Exercises and Solutions heading and the first lesson plan in the list. Space should match all of the other sections on the TR page. Merci!

**Comment by schanzer** [comment]
@flannery-denny whitespace removed!

**Pull request merged**
