### PR TITLE
Flex wbpages

### PR DESCRIPTION
**Pull request by schanzer**
Ready for another round of pdf review, with edits to 300 files.

Almost _nine hundred_ lines of brittle code have been removed, AND I've unified the following classes into two: `.studentAnswer`, `.studentAnswerFilled`, `.studentAnswerUnfilled`, `.fitb`, and `.fitbruby`. Now, the extra vertical height we give kids to write is declared in a _single line of CSS_, allowing us to use consistent formatting across every place where students write things. 

- [x] Merge better-dr improvements
- [x] Use LESS CSS variables?
- [x] Merge conditional-dr branch improvements
- [x] Move acknowledgement section to _after_ the page bottom
- [x] Fix tall headers
- [x] Make contracts pages in back-matter print with headers all facing the same direction

### CODE REVIEW

**Comment by retabak** [comment]
in workbook-long for CODAP...

p. 25, too much space at top:
image

design recipes, i.e. p. 28:
The line on which students are to write Tranformer name seem really squished. There's also a lot of space under the directions.
image

The top half of this page (p. 30) looks vertically squished:
image

"What's on your mind" (p.31) should fill up the whole page, right?
image

**Comment by flannery-denny** [comment]
@schanzer 
- [ ] Frayer Model 1 and Frayer Model 2 are identical. The second should not be focused on Domain and Range.

**Comment by schanzer** [comment]
@retabak I've added an extra 25% whitespace to the blank lines in the DR template, and addressed the other issues as well.
@flannery-denny sorry about the Frayer issue - copy/paste bug on my part. As for the links: the _individual_ PDFs work (like the ones people can easily access on the web), but the links in the combined, printed workbook don't. This is due to some kind of bug in the pdf-merging library, which unfortunately we can't easily fix. The good news is that by far the most common use-case is that someone loads a workbook page, opens the PDF, and clicks a link -- and those continue to work.

**Comment by flannery-denny** [comment]
@schanzer pushing a bunch of small fixes. Added more checkboxes to my comment. Don't understand how that bug would allow some links to work and others not... I would have guessed it has something to do with how our directives are constructed.

**Comment by schanzer** [comment]
@flannery-denny none of the links in the compiled workbook function. All the links _outside_ the workbook do.

**Comment by flannery-denny** [comment]
@schanzer not true. Build algebra-wescheme workbook long. Go to page 68 of
the pdf. The link is clickable.[image: Screen Shot 2022-10-14 at 9.49.10
AM.png]

**Comment by schanzer** [comment]
@flannery-denny ah, GREAT catch! This is truly interesting.

That specific page is NOT generated using our html->pdf infrastructure. Try opening inequalities1-simple/pages/boolean-functions.pdf (the individual page), and hovering over the link. It's clickable, and the arrow turns into a hand. But do the same in the guide page, and there's a totally different behavior!

Apparently there are multiple ways to embed a link in a PDF, and the pdf merging library only preserves one of them. I will look into this.

**Comment by retabak** [comment]
page 6 - lots of space before "Data Types":
image

page 8 - extra space after the directions / before "Numbers":
image

**Comment by flannery-denny** [comment]
- [ ] I'm noticing that the vertical spacing on contracts/code isn't generous enough. The bottom of `g` is getting cut off. Here are two examples (notice that the formatting of these is different so they likely come from two different kinds of asciidoc coding)
Screen Shot 2022-10-26 at 11 35 53 AM

Screen Shot 2022-10-26 at 11 31 15 AM
- [ ] This is not the cause of your pull request, and predates my time on the team, but I'm noticing that the text at the top of the `flags-of-the-world.pdf` states that the flags can all be made with `overlay, beside, and above`... and some of them definitely require `put-image`!
- [ ] I'm not sure what the arc of reactive is, but it feels like there are probably more Design Recipe word problems that that course needs
- [ ] What is the purpose of this page? I would expect notes here, given the title.
Screen Shot 2022-10-26 at 12 10 34 PM
- [ ] This page could use `@fitb{}`
Screen Shot 2022-10-26 at 12 11 49 PM
- [ ] Confirming the `|` really belongs on this page. I've never seen it used in a contract before. Also, this exact same page appears in the workbook twice, back to back.
Screen Shot 2022-10-26 at 12 13 10 PM
- [ ] There is no reference to Unit 1 or Unit 2 and then, suddenly, here we are at Unit 3, where it's also unclear why you are providing a page of blank lines rather than notes.
Screen Shot 2022-10-26 at 12 15 02 PM
- [ ] Not sure why each of these lines starts with `{}`. Seems like they're either unintentional or you mean to leave space for something the be written between them?
Screen Shot 2022-10-26 at 12 16 20 PM
- [ ] There are 4 pairs of pages titled `Identifying Animation Data Worksheet` and `Design a Data Structure` and none could be completed without directions that would have to come from the teacher. Is this intentional?
- [ ] This page could take better advantage of your new vertical spacing mechanism.
Screen Shot 2022-10-26 at 12 19 43 PM
- [ ] Strange that this page has no heading... and it looks like the `@fitb{}` are overlapping. This page style gets reused and they all have the same issues.
Screen Shot 2022-10-26 at 12 28 58 PM
- [ ] The Design Recipe problems unique to this pathway are not taking advantage of `@funname` formatting.
- [ ] Again, Why this page?
Screen Shot 2022-10-26 at 12 24 24 PM
- [ ] Do you mean to have this To Do checked? Are you ok with the table overlapping the page number?
Screen Shot 2022-10-26 at 12 25 36 PM
- [ ] Another page for taking advantage of your vertical spacing mechanism
Screen Shot 2022-10-26 at 12 25 15 PM
- [ ] These same directions appear on several pages. Unclear to me why it would be useful to give the same directions more than once. `Decrease the cat’s hunger level by 2 and sleep level by 1 on each tick.`
- [ ] Again, why? Also, if you actually want to keep these pages, the lines don't fill the page.
Screen Shot 2022-10-26 at 12 33 19 PM
Screen Shot 2022-10-26 at 12 33 39 PM
Screen Shot 2022-10-26 at 12 34 21 PM
Screen Shot 2022-10-26 at 12 34 33 PM
Screen Shot 2022-10-26 at 12 37 08 PM
Screen Shot 2022-10-26 at 12 37 14 PM
Screen Shot 2022-10-26 at 12 37 22 PM
- [ ] Is reactive really in Pyret? or WeScheme? Do you want to provide a hint about the `sqrt` function like we do in algebra?
Screen Shot 2022-10-26 at 12 35 16 PM
- [ ] I'm not convinced that the contract page contains the right contracts for this pathway. I suggested an audit.

**Comment by schanzer** [comment]
@flannery-denny thanks - I've made the following changes:

- @funname is used for DR pages in the Reactive pathway
- Corrected the visual glitches you reported, so page numbers don't stomp on page content and FillVerticalSpace is used where it should be
- Removed extraneous reference to "Unit 3"
- Fixed instructions on "Flags of the World"
- Added line-height to multiline code displays, so lines don't touch one another

There are several things that are not going to be fixed, however:

- Those notes pages with tons of blank lines can't be removed, since that will mess up page numbers in the workbook. Someday it would be nice to add notes to those pages, but this isn't the time. I've added a checkbox for this to #184
- The animations worksheets are all supposed to be about the virtual pet, so those instructions are valid
- The worksheets that need the teachers' instruction need to be fixed, but not now. Added to #184 
- The underscores on the CakeType page are there because there's no way use `@fitb` and still get proper code formatting. The same issue crops up in `grouped-samples` when we try to give kids function templates.

I've removed the 6-8 pages of notes page screenshots from your comment, just to improve readability.

**Comment by retabak** [comment]
in workbook-long for codap:

- [ ] p9- some extra space
image

workbook-long for wescheme:

- [ ] p19 - extra space before "Numbers" heading 
image

- [ ] "quick guide to saving images" (PDF p69)- it's two pages, so only one page shows up. This was commented on in June (issue #1016). We should actually fix this at some point! [not related to this PR, I suppose]

- [ ] spacing looks odd here; can we move the tables a bit more toward the center of the page?
image

- [ ] design recipes look squished throughout; can they fill up the page?
image

- [ ] this also feels squished / crowded:
image

- [ ] and this (kids might want space to show work?):
image

- [ ]  would be nice for these to use up the whole page
image

- [ ] why is the parenthese trailing onto the next line?
image

- [ ] is this page supposed to be blank?
image

**Comment by flannery-denny** [comment]
@retabak that Sally's bike page is an opt-printable exercise that allows teachers to go full circle and have their students complete the word problem that was the hook for the lesson plan. It is not compatible with the design recipe and should not have additional scaffolding

**Comment by schanzer** [comment]
@retabak thanks! I fixed most of the issues you reported. Getting those "Linear, Non-Linear or Bust" pages working was something I'd been putting off because it's a messy change, but this was enough of a push to make me sit down and work it out.

The one issue I'm not able to fix is that trailing parenthesis on the EXAMPLE page. I can't reproduce it on my machine! Does it show up reliably for you?

**Comment by flannery-denny** [comment]
@schanzer 
- [ ] The `Function` and `Variable` Frayer Model has the word `Domain` in the first oval.
- [ ] The instructions for the `flags-of-the-word.pdf` still don't say anything about using `put-image`
- [ ] If you're not going to use `@fitb{}` on the `DataStructure: Cake Type` page, please add vertical space between the three lines made of underscores. There is definitely not enough room to write anything here.
- [ ] The notes pages with blank lines still only have blank lines filling about 2/3 of the page.
- [ ] I thought I'd flagged this style of pages in my first round of feedback for strange formatting but am not seeing them in the issue... 
Screen Shot 2022-10-27 at 12 14 15 PM
- [ ] I also thought that I'd flagged this page for lack of scaffolding in my first round of feedback. 
Screen Shot 2022-10-27 at 12 15 54 PM
Here's what the scaffolding looks like in the algebra pathway.
- [ ] flagging that none of the pages unique to reactive (DR or otherwise) provide solutions in the solution book

**Comment by flannery-denny** [comment]
@schanzer I also took a quick pass at the OK workbook. Here are some things I noticed.
- [ ] else if formatting is strange
Screen Shot 2022-10-27 at 2 46 55 PM
- [ ] the table on reading row and function definitions is out of alignment
Screen Shot 2022-10-27 at 2 47 18 PM
- [ ] there are examples given for `name-has-s`. Is that intentional?
Screen Shot 2022-10-27 at 2 48 05 PM
- [ ] The line spacing on the what's on your mind pages has gotten smaller again. We used to use a separate directive for keeping line spacing larger on some pages (not just these! I occasionally used it as an authoring tool)
Screen Shot 2022-10-27 at 2 48 31 PM
Here's what the spacing looks like in the workbook available for download from our website
Screen Shot 2022-10-27 at 2 54 02 PM
- [ ] The great `gt` domain debate question 2 lands on the lines... not sure why.
Screen Shot 2022-10-27 at 2 40 54 PM

**Comment by schanzer** [comment]
@flannery-denny this is weird - I found a number of regressions on my machine (including a corrupted node_modules directory!). I have once again pushed fixes to most of the issues above:

- Using fitb inside a code block is impossible, but for CakeType I decided to give up on syntax highlighting and just make everything use a code _font_. This allowed me to use fitb after all.
- The lack of scaffolding and solutions for various reactive pages is intentional
- I abandoned the "every fill in the blank has the same hight" goal in order to give you the extra space you wanted. Now, Design Recipes have about 15% less vertical space for kids to write on than other spaces. There is no special directive for tall blank lines, however -- all blanks outside of DRs use either fitb or fitbruby.
- Fixed a number of small asciidoc errors on various wbpages, which were causing glitches like the one you reported on the great GT domain debate.

I believe this branch is now ready to merge!

**Comment by retabak** [comment]
Here are the issues I still see in workbook-long wescheme:

- [ ] page 19 looks the same - too much space beneath the directions
- [ ] "quick guide to saving images" (PDF p69)- still two pages
- [ ] the parenthese is still trailing! (PDF p. 113) and yes, it is showing up reliably.

**Comment by schanzer** [comment]
@retabak I absolutely fixed page 19 -- somehow several of the commits I made for both you and flannery got lost yesterday, and it's freaking me out. Anyway, I've re-pushed.

I think Flannery already talked about the guide to saving PDFs. It's _supposed_ to be two pages, so this is *not* a bug! I have a solution: now that we have `@handout`, we no longer need to use `opt-printable-exercise` to include it in the workbook. That's probably the best solution.

I'm going to consciously ignore the paren for now. It seems like it's ONLY showing up for you on that one page, and only for you specifically. I think we can merge with that one loose end.

@flannery-denny and @retabak , I hate to ask you to check the most recent commit yet again, but given that some fixes didn't make it in last time I'm feeling a little paranoid. Can you check the issues that lingered as of yesterday?

**Comment by retabak** [comment]
I got some warnings when building algebra-wescheme; flagging these just to be sure ntohign is getting cut off - 
                                                                                                                                                                                                `WARNING: in algebra-wescheme workbook-long.pdf, ../../lessons/functions-can-be-linear-wescheme/pages/linear-nonlinear-bust.pdf has 2 pages                                                                                                                                                                                                                                                      WARNING: in algebra-wescheme workbook-long-sols.pdf, ../../lessons/functions-examples-definitions-wescheme/solution-pages/MappingExamplesWithCoE.pdf has 2 pages                                                                                                                                                                                                                              WARNING: in algebra-wescheme workbook-long-sols.pdf, ../../lessons/functions-examples-definitions-wescheme/solution-pages/match-contracts-examples2.pdf has 2 pages          
`
Unrelated to this PR: wescheme-long - p. 104 and p. 107 both have little squiggly underlines indicating misspelled words 

codap workbook-long:
p. 13 got messed up!? I think this was resolved before?
![image](https://user-images.githubusercontent.com/87144723/199289769-ad2f1da3-3ce2-4d74-8cc2-b5a06507b76e.png)

p.18 looks funny too:
![image](https://user-images.githubusercontent.com/87144723/199289925-052200f3-6c6d-494a-88b5-3fbb3b424397.png)

p.19 - should "data cycle" fill up the entire page?
![image](https://user-images.githubusercontent.com/87144723/199290094-78a8e77c-21ae-4969-aba1-db77a0ef2be7.png)

warnings when I build codap:

`WARNING: in data-science-codap workbook-long.pdf, ../../lessons/data-cycle-codap/pages/which-question-type.pdf has 2 pages`

**Comment by flannery-denny** [comment]
@schanzer 
- [ ] flags of the world pdf is still missing the `put-image` function.
- [ ]  The notes pages with blank lines still only have blank lines filling about 2/3 of the page.
- [ ] The last line of the **What's on your mind** page lands on the page number.
- [ ] Still no solutions provided for reactive DR pages

**Pull request merged**
